services:
  database:
    image: postgres:17
    ports:
      - "8080:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: wb-l2
    volumes:
      - ./develop/dev11/init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
